Repository takeoff-26/logistics-service, pull requests merged in 2025-03, with the labels that each got.

#2 Feature/#1 PR 예시 및 gateway 추가
  gateway/.gitattributes
  gateway/.gitignore
  gateway/build.gradle
  gateway/gradle/wrapper/gradle-wrapper.jar
  gateway/gradle/wrapper/gradle-wrapper.properties
  gateway/gradlew
  gateway/settings.gradle
  gateway/src/main/java/takeoff/logistics_service/msa/gateway/GatewayApplication.java
  gateway/src/main/resources/application.properties
  gateway/src/test/java/takeoff/logistics_service/msa/gateway/GatewayApplicationTests.java
Labels: ⚙️ setting

#5 Feature/#4 개발환경 세팅
  .gitignore
  docker-compose.yml
  server/build.gradle
  server/src/main/java/takeoff/logistics_service/msa/server/ServerApplication.java
  server/src/main/resources/application.properties
  settings.gradle
Labels: ⚙️ setting

#9 Feature/#3 공통 모듈 추가 및 초기 세팅
  common/.gitattributes
  common/.gitignore
  common/build.gradle
  common/gradle/wrapper/gradle-wrapper.jar
  common/gradle/wrapper/gradle-wrapper.properties
  common/gradlew
  common/settings.gradle
  common/src/main/resources/application.yml
  common/src/test/java/takeoff/logistics_service/msa/common/CommonApplicationTests.java
  init.sql
  server/src/main/resources/application.yml
  settings.gradle
Labels: ⚙️ setting

#12 feature/#11: 공통 예외 응답 클래스 생성
  common/.gitattributes
  common/.gitignore
  common/gradlew
  common/settings.gradle
  common/src/main/java/takeoff/logistics_service/msa/common/exception/ErrorResponse.java
  common/src/main/java/takeoff/logistics_service/msa/common/exception/GlobalExceptionHandler.java
  common/src/main/java/takeoff/logistics_service/msa/common/exception/customexceptions/BusinessException.java
  common/src/main/java/takeoff/logistics_service/msa/common/exception/errorcodes/ErrorCode.java
  common/src/main/java/takeoff/logistics_service/msa/common/exception/errorcodes/enums/CommonErrorCode.java
Labels: ✨ feat

#17 refactor/#16 Slack 리팩토링
  slack/src/main/java/takeoff/logistics_service/msa/slack/application/service/SlackService.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/application/service/SlackServiceImpl.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/infrastructure/persistence/JpaSlackRepositoryCustom.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/infrastructure/persistence/impl/JpaSlackRepositoryCustomImpl.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/model/repository/SlackRepository.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/request/GetContentsRequestDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/request/GetSlackRequestDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/request/PatchContentsRequestDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/request/PatchSlackRequestDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/request/PostContentsRequestDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/request/PostSlackRequestDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/request/SearchContentsRequestDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/request/SearchSlackRequestDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/response/GetContentsResponseDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/response/GetSlackResponseDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/response/PatchContentsResponseDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/response/PatchSlackResponseDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/response/PostContentsResponseDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/response/PostSlackResponseDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/response/SearchContentsResponseDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/response/SearchSlackResponseDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/response/SlackResponseDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/external/SlackExternalController.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/internal/SlackInternalController.java
Labels: ♻️ refactor

#21 Feature/#10
  product/build.gradle
  product/gradle/wrapper/gradle-wrapper.jar
  product/gradle/wrapper/gradle-wrapper.properties
  product/src/main/java/takeoff/logistics_service/msa/product/ProductApplication.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/model/entity/Product.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/service/StockService.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/service/StockServiceImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/config/QueryDslConfig.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/persistence/JpaStockRepository.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/persistence/JpaStockRepositoryCustom.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/persistence/impl/JpaStockRepositoryCustomImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/model/entity/Stock.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/model/entity/StockId.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/model/repository/StockRepository.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/dto/StockIdDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/dto/request/AbortStockRequestDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/dto/request/DecreaseStockRequestDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/dto/request/IncreaseStockRequestDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/dto/request/PostStockRequestDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/dto/request/PrepareStockRequestDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/dto/request/StockItemRequestDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/dto/response/DecreaseStockResponseDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/dto/response/GetStockResponseDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/dto/response/IncreaseStockResponseDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/dto/response/PostStockResponseDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/external/StockExternalController.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/internal/StockInternalController.java
  product/src/main/resources/application.yml
  product/src/test/java/takeoff/logistics_service/msa/product/ProductApplicationTests.java
  settings.gradle
Labels: ✨ feat, ⚙️ setting

#22 feature/#8: 사용자 초기 환경 세팅 및 엔티티, 애그리거트, VO 생성
  HELP.md
  company/.gitattributes
  company/.gitignore
  company/build.gradle
  company/gradle/wrapper/gradle-wrapper.jar
  company/gradle/wrapper/gradle-wrapper.properties
  company/gradlew
  company/settings.gradle
  company/src/main/java/takeoff/logistics_service/msa/company/CompanyApplication.java
  company/src/main/resources/application.yml
  company/src/test/java/com/logistics/company/CompanyApplicationTests.java
  docker-compose.yml
  gateway/src/main/resources/application.properties
  gateway/src/main/resources/application.yml
  settings.gradle
  user/.gitattributes
  user/.gitignore
  user/build.gradle
  user/gradle/wrapper/gradle-wrapper.jar
  user/gradle/wrapper/gradle-wrapper.properties
  user/gradlew
  user/settings.gradle
  user/src/main/java/takeoff/logistics_service/msa/user/UserApplication.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/CompanyDeliveryManager.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/DeliveryManager.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/HubDeliveryManager.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/User.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/UserRole.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/repository/UserRepository.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/vo/CompanyId.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/vo/DeliverySequence.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/vo/HubId.java
  user/src/main/resources/application.yml
  user/src/test/java/com/logistics/user/UserApplicationTests.java
Labels: ✨ feat, ⚙️ setting

#27 Fix/#24 재고 변경 로직 수정 및 공통모듈 수정
  common/build.gradle
  common/src/main/java/takeoff/logistics_service/msa/common/domain/BaseEntity.java
  common/src/main/java/takeoff/logistics_service/msa/common/exception/BusinessException.java
  common/src/main/java/takeoff/logistics_service/msa/common/exception/ErrorResponse.java
  common/src/main/java/takeoff/logistics_service/msa/common/exception/GlobalExceptionHandler.java
  common/src/main/java/takeoff/logistics_service/msa/common/exception/code/CommonErrorCode.java
  common/src/main/java/takeoff/logistics_service/msa/common/exception/code/ErrorCode.java
  product/build.gradle
  product/src/main/java/takeoff/logistics_service/msa/product/ProductApplication.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/exception/StockBusinessException.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/exception/StockErrorCode.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/service/StockService.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/service/StockServiceImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/persistence/JpaStockRepository.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/persistence/JpaStockRepositoryCustom.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/persistence/impl/JpaStockRepositoryCustomImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/model/entity/Stock.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/model/repository/StockRepository.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/dto/request/StockSearchCondition.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/dto/response/GetStockResponseDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/dto/response/PostStockResponseDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/external/StockExternalController.java
  product/src/main/resources/application.yml
  product/src/main/resources/http/stock/external.http
  product/src/main/resources/http/stock/internal.http
  product/src/test/java/takeoff/logistics_service/msa/product/stock/application/service/StockServiceConcurrencyTest.java
Labels: ✨ feat, 🐛 bug

#25 Feature/#20 HubRoute RUD
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/application/service/HubRouteService.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/application/service/HubRouteServiceImpl.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/infrastructure/persistence/JpaHubRouteRepository.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/model/entity/Distance.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/model/entity/Duration.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/model/entity/HubRoute.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/model/repository/HubRouteRepository.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/presentation/dto/request/PostHubRouteRequestDto.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/presentation/dto/request/PutHubRouteRequestDto.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/presentation/dto/response/GetHubRouteResponseDto.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/presentation/dto/response/PostHubRouteResponseDto.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/presentation/dto/response/PutHubRouteResponseDto.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/presentation/external/HubRouteExternalController.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/presentation/internal/HubRouteInternalController.java
Labels: ✨ feat

#29 Feature/#26 slack 도메인 요구사항 충족
  slack/build.gradle
  slack/src/main/java/takeoff/logistics_service/msa/slack/SlackApplication.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/application/service/SlackAlarmService.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/application/service/SlackService.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/application/service/SlackServiceImpl.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/infrastructure/client/ai/AiPromptEnum.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/infrastructure/client/ai/GeminiWebClient.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/infrastructure/config/WebClientConfig.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/infrastructure/persistence/impl/JpaSlackRepositoryCustomImpl.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/model/entity/Contents.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/model/entity/SlackConstant.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/model/repository/SlackRepository.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/DeliveryUsers.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/StopoverHubNames.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/request/GetContentsRequestDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/request/GetSlackRequestDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/request/PatchContentsRequestDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/request/PatchSlackRequestDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/request/PostContentsRequestDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/request/PostSlackMessageRequestDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/request/PostSlackRequestDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/request/SearchContentsRequestDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/request/SearchSlackRequestDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/response/PostSlackResponseDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/external/SlackExternalController.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/internal/SlackInternalController.java
  slack/src/main/resources/application.yml
  slack/src/test/java/takeoff/logistics_service/msa/slack/httpclient/slackHttpClient.http
Labels: ✨ feat, ♻️ refactor

#31 Feature/#7 [order] 주문 생성 #7
  delivery/build.gradle
  delivery/gradle/wrapper/gradle-wrapper.jar
  delivery/gradle/wrapper/gradle-wrapper.properties
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/DeliveryApplication.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/application/DeliveryService.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/infrastructure/JpaDeliveryRepository.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/model/entity/Delivery.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/model/entity/DeliveryId.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/model/entity/DeliveryStatus.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/model/repository/DeliveryRepository.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/presentation/dto/PostDeliveryRequestDto.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/presentation/internal/DeliveryInternalController.java
  delivery/src/main/resources/application.yml
  delivery/src/test/java/takeoff/logisticsservice/msa/delivery/DeliveryApplicationTests.java
  order/build.gradle
  order/gradle/wrapper/gradle-wrapper.jar
  order/gradle/wrapper/gradle-wrapper.properties
  order/src/main/java/takeoff/logistics_service/msa/order/OrderApplication.java
  order/src/main/java/takeoff/logistics_service/msa/order/application/client/DeliveryClient.java
  order/src/main/java/takeoff/logistics_service/msa/order/application/service/OrderService.java
  order/src/main/java/takeoff/logistics_service/msa/order/infrastructure/JpaOrderRepository.java
  order/src/main/java/takeoff/logistics_service/msa/order/model/entity/Order.java
  order/src/main/java/takeoff/logistics_service/msa/order/model/entity/OrderId.java
  order/src/main/java/takeoff/logistics_service/msa/order/model/entity/OrderItem.java
  order/src/main/java/takeoff/logistics_service/msa/order/model/entity/OrderItemId.java
  order/src/main/java/takeoff/logistics_service/msa/order/model/repository/OrderRepository.java
  order/src/main/java/takeoff/logistics_service/msa/order/presentation/dto/external/OrderController.java
  order/src/main/java/takeoff/logistics_service/msa/order/presentation/dto/request/OrderItemSaveRequestDto.java
  order/src/main/java/takeoff/logistics_service/msa/order/presentation/dto/request/OrderSaveRequestDto.java
  order/src/main/java/takeoff/logistics_service/msa/order/presentation/dto/response/OrderSaveResponseDto.java
  order/src/main/resources/application.yml
  order/src/test/java/takeoff/logistics_service/msa/order/OrderApplicationTests.java
  server/src/main/resources/application.yml
  settings.gradle
Labels: ✨ feat

#37 feature/28: 상품 CRUD 구현
  gateway/build.gradle
  gateway/src/main/resources/application.yml
  product/src/main/java/takeoff/logistics_service/msa/product/ProductApplication.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/dto/request/PatchProductRequestDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/dto/request/PostProductRequestDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/dto/request/PostStockRequestDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/dto/response/GetProductResponseDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/dto/response/PatchProductResponseDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/dto/response/PostProductResponseDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/dto/response/PostStockResponseDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/exception/ProductBusinessException.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/exception/ProductErrorCode.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/service/ProductService.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/service/ProductServiceImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/service/StockClient.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignStockClient.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignStockClientImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/dto/request/PostStockRequest.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/dto/request/StockIdRequest.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/dto/response/PostStockResponse.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/dto/response/StockIdResponse.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/config/QueryDslConfig.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/persistence/JpaProductRepository.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/persistence/JpaProductRepositoryCustom.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/persistence/impl/JpaProductRepositoryCustomImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/model/command/CreateProduct.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/model/command/ModifyProduct.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/model/entity/Product.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/model/repository/ProductRepository.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/presentation/dto/request/PatchProductRequest.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/presentation/dto/request/PostProductRequest.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/presentation/dto/response/GetProductResponse.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/presentation/dto/response/PatchProductResponse.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/presentation/dto/response/PostProductResponse.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/presentation/external/ProductExternalController.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/dto/StockSearchCondition.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/exception/StockBusinessException.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/exception/StockErrorCode.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/service/StockService.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/service/StockServiceImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/persistence/JpaStockRepository.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/persistence/JpaStockRepositoryCustom.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/persistence/impl/JpaStockRepositoryCustomImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/model/entity/Stock.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/model/entity/StockId.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/model/repository/StockRepository.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/dto/request/PostStockRequestDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/external/StockExternalController.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/internal/StockInternalController.java
  product/src/main/resources/http/product/external.http
Labels: ✨ feat

#44 Feature#38: 배송 담당자 CRUD 구현
  user/build.gradle
  user/src/main/java/takeoff/logistics_service/msa/user/UserApplication.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/service/DeliveryManagerService.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/service/DeliveryManagerServiceImpl.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/service/UserService.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/service/UserServiceImpl.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/CompanyDeliveryManager.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/DeliveryManager.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/HubDeliveryManager.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/User.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/repository/UserRepository.java
  user/src/main/java/takeoff/logistics_service/msa/user/infrastructure/persistence/JpaUserRepository.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/request/DeleteDeliveryManagerRequestDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/request/GetUserRequestDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/request/PatchDeliveryManagerRequestDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/request/PatchUserRequestDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/request/PostDeliveryManagerRequestDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/response/DeleteDeliveryManagerResponseDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/response/DeleteUserResponseDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/response/GetDeliveryManagerResponseDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/response/GetUserListResponseDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/response/PatchDeliveryManagerResponseDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/response/PostDeliveryManagerResponseDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/external/DeliveryManagerExternalController.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/external/UserExternalController.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/internal/DeliveryManagerInternalController.java
  user/src/main/resources/application.yml
Labels: ✨ feat, ♻️ refactor

#50 feature/#48: [fix]build.gradle수정
  company/.gitattributes
  company/.gitignore
  company/gradlew
  company/settings.gradle
  user/.gitattributes
  user/.gitignore
  user/build.gradle
  user/gradlew
  user/settings.gradle
Labels: 🐛 bug, ⚙️ setting

#56 Feature/#53 상품중에 남은재고있는 허브 알려주는 내부api 구현
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/service/StockService.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/service/StockServiceImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/domain/entity/Stock.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/domain/repository/StockRepository.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/persistence/JpaStockRepository.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/persistence/aspect/LockTimeoutAspect.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/internal/StockInternalController.java
  product/src/main/resources/http/stock/internal.http
  product/src/test/java/takeoff/logistics_service/msa/product/stock/infrastructure/persistence/aspect/LockTimeoutAspectTest.java
Labels: ✨ feat, ♻️ refactor

#60 feature/#57 업체 cruds 구현
  company/build.gradle
  company/src/main/java/takeoff/logistics_service/msa/company/CompanyApplication.java
  company/src/main/java/takeoff/logistics_service/msa/company/application/dto/request/PostCompanyRequestDto.java
  company/src/main/java/takeoff/logistics_service/msa/company/application/dto/request/PutCompanyRequestDto.java
  company/src/main/java/takeoff/logistics_service/msa/company/application/dto/request/SearchCompanyRequestDto.java
  company/src/main/java/takeoff/logistics_service/msa/company/application/dto/response/GetCompanyResponseDto.java
  company/src/main/java/takeoff/logistics_service/msa/company/application/dto/response/PaginatedResultDto.java
  company/src/main/java/takeoff/logistics_service/msa/company/application/dto/response/PostCompanyResponseDto.java
  company/src/main/java/takeoff/logistics_service/msa/company/application/dto/response/PutCompanyResponseDto.java
  company/src/main/java/takeoff/logistics_service/msa/company/application/exception/CompanyBusinessException.java
  company/src/main/java/takeoff/logistics_service/msa/company/application/exception/CompanyErrorCode.java
  company/src/main/java/takeoff/logistics_service/msa/company/application/service/CompanyService.java
  company/src/main/java/takeoff/logistics_service/msa/company/application/service/CompanyServiceImpl.java
  company/src/main/java/takeoff/logistics_service/msa/company/domain/command/CreateCompany.java
  company/src/main/java/takeoff/logistics_service/msa/company/domain/command/ModifyCompany.java
  company/src/main/java/takeoff/logistics_service/msa/company/domain/entity/Company.java
  company/src/main/java/takeoff/logistics_service/msa/company/domain/entity/CompanyType.java
  company/src/main/java/takeoff/logistics_service/msa/company/domain/repository/CompanyRepository.java
  company/src/main/java/takeoff/logistics_service/msa/company/domain/repository/search/CompanySearchCriteria.java
  company/src/main/java/takeoff/logistics_service/msa/company/domain/repository/search/CompanySearchCriteriaResponse.java
  company/src/main/java/takeoff/logistics_service/msa/company/domain/repository/search/PaginatedResult.java
  company/src/main/java/takeoff/logistics_service/msa/company/infrastructure/persistence/JpaCompanyRepository.java
  company/src/main/java/takeoff/logistics_service/msa/company/infrastructure/persistence/JpaCompanyRepositoryCustom.java
  company/src/main/java/takeoff/logistics_service/msa/company/infrastructure/persistence/config/QueryDslConfig.java
  company/src/main/java/takeoff/logistics_service/msa/company/infrastructure/persistence/impl/JpaCompanyRepositoryCustomImpl.java
  company/src/main/java/takeoff/logistics_service/msa/company/presentation/dto/request/PostCompanyRequest.java
  company/src/main/java/takeoff/logistics_service/msa/company/presentation/dto/request/PutCompanyRequest.java
  company/src/main/java/takeoff/logistics_service/msa/company/presentation/dto/request/SearchCompanyRequest.java
  company/src/main/java/takeoff/logistics_service/msa/company/presentation/dto/response/GetCompanyResponse.java
  company/src/main/java/takeoff/logistics_service/msa/company/presentation/dto/response/PaginatedResultApi.java
  company/src/main/java/takeoff/logistics_service/msa/company/presentation/dto/response/PostCompanyResponse.java
  company/src/main/java/takeoff/logistics_service/msa/company/presentation/dto/response/PutCompanyResponse.java
  company/src/main/java/takeoff/logistics_service/msa/company/presentation/external/CompanyExternalController.java
  company/src/main/java/takeoff/logistics_service/msa/company/presentation/internal/CompanyInternalController.java
  company/src/main/resources/application.yml
  company/src/main/resources/http/company/external.http
Labels: ✨ feat

#63 Feature/#61 상품 생성시 검증 로직 추가
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/exception/ProductErrorCode.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/service/CompanyClient.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/service/HubClient.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/service/ProductServiceImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignCompanyClient.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignCompanyClientImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignHubClient.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignHubClientImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/dto/response/GetCompanyResponse.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/dto/response/GetHubResponse.java
Labels: ✨ feat, ♻️ refactor

#72 feature/#51: auth-service(인증서버) 구현
  auth/build.gradle
  auth/gradle/wrapper/gradle-wrapper.jar
  auth/gradle/wrapper/gradle-wrapper.properties
  auth/src/main/java/takeoff/logistics_service/msa/auth/AuthApplication.java
  auth/src/main/resources/application.yml
  auth/src/test/java/takeoff/logistics_service/msa/auth/AuthApplicationTests.java
Labels: ✨ feat, ⚙️ setting

#79 Feature/#66 slack, hub, hubroute 요구사항 수정
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/application/dto/PaginatedResultDto.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/application/dto/request/SearchHubRequestDto.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/application/service/HubServiceImpl.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/application/service/HubRouteServiceImpl.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/presentation/external/HubRouteExternalController.java
  hub/src/test/java/takeoff/logistics_service/msa/hub/http/Hub.http
  hub/src/test/java/takeoff/logistics_service/msa/hub/http/HubCreate.http
  hub/src/test/java/takeoff/logistics_service/msa/hub/http/HubRouteExternal.http
  hub/src/test/java/takeoff/logistics_service/msa/hub/http/HubRouteInternal.http
  slack/src/main/java/takeoff/logistics_service/msa/slack/application/dto/request/PostContentsRequestDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/application/dto/request/PostUserSlackRequestDto.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/application/service/SlackAlarmService.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/application/service/SlackConstant.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/application/service/SlackService.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/application/service/SlackServiceImpl.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/request/PostContentsRequest.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/request/PostUserSlackRequest.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/internal/SlackInternalController.java
  slack/src/test/java/takeoff/logistics_service/msa/slack/httpclient/slackHttpClient.http
Labels: ✨ feat, ✅ test

#82 Feature/#65 hub, hubRoute WireMock 테스트
  hub/build.gradle
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/application/dto/DistanceDto.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/application/dto/request/PostHubRouteRequestDto.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/application/dto/response/GetHubRouteNaverResponseDto.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/application/dto/response/PostHubRouteResponseDto.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/application/service/HubRouteServiceImpl.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/infrastructure/dto/response/GetRouteResponse.java
  hub/src/main/resources/application-test.yml
  hub/src/test/java/takeoff/logistics_service/msa/hub/hubroute/application/service/wiremock/OpenFeignClientTest.java
Labels: ✨ feat, ✅ test

#86 Docs/#68 product, stock 테스트코드 작성 및 api 문서 자동화
  gateway/build.gradle
  gateway/src/main/resources/application.yml
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/application/service/HubRouteServiceImpl.java
  product/build.gradle
  product/src/docs/tag-descriptions.yaml
  product/src/main/resources/application.yml
  product/src/test/java/takeoff/logistics_service/msa/product/product/presentation/external/ProductExternalControllerTest.java
  product/src/test/java/takeoff/logistics_service/msa/product/stock/presentation/external/StockExternalControllerTest.java
  product/src/test/java/takeoff/logistics_service/msa/product/stock/presentation/internal/StockInternalControllerTest.java
Labels: 📖️docs

#88 docs/#87 swagger 예쁘게 만들어 올리기
  gateway/src/main/resources/application.yml
  hub/build.gradle
  hub/src/docs/tag-descriptions.yaml
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/application/dto/client/NaverRequestClient.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/application/service/HubRouteServiceImpl.java
  hub/src/main/resources/application.yml
  hub/src/test/java/takeoff/logistics_service/msa/hub/hub/presentation/external/HubExternalControllerTest.java
  hub/src/test/java/takeoff/logistics_service/msa/hub/hub/presentation/internal/HubInternalControllerTest.java
  hub/src/test/java/takeoff/logistics_service/msa/hub/hubroute/presentation/external/HubRouteExternalControllerTest.java
  hub/src/test/java/takeoff/logistics_service/msa/hub/hubroute/presentation/internal/HubRouteInternalControllerTest.java
  slack/build.gradle
  slack/src/docs/tag-descriptions.yaml
  slack/src/main/resources/application.yml
  slack/src/test/java/takeoff/logistics_service/msa/slack/presentation/external/SlackExternalControllerTest.java
  slack/src/test/java/takeoff/logistics_service/msa/slack/presentation/internal/SlackInternalControllerTest.java
Labels: 📖️docs

#91 Feature#71: API GatewayGlobalFilter 추가, Jwt검증 util클래스 구현, E2E테스트 환경세팅
  auth/src/main/java/takeoff/logistics_service/msa/auth/application/client/UserServiceFeignClient.java
  auth/src/main/java/takeoff/logistics_service/msa/auth/application/service/AuthService.java
  auth/src/main/java/takeoff/logistics_service/msa/auth/application/service/TokenService.java
  auth/src/main/java/takeoff/logistics_service/msa/auth/domain/service/RedisTokenService.java
  auth/src/main/java/takeoff/logistics_service/msa/auth/infrastructure/config/RedisConfig.java
  auth/src/main/java/takeoff/logistics_service/msa/auth/infrastructure/config/SecurityConfig.java
  auth/src/main/java/takeoff/logistics_service/msa/auth/infrastructure/security/JwtAuthenticationFilter.java
  auth/src/main/java/takeoff/logistics_service/msa/auth/presentation/controller/AuthController.java
  auth/src/main/resources/application.yml
  gateway/build.gradle
  gateway/src/main/java/takeoff/logistics_service/msa/gateway/security/GatewayJwtFilter.java
  gateway/src/main/java/takeoff/logistics_service/msa/gateway/security/GatewaySecurityConfig.java
  gateway/src/main/java/takeoff/logistics_service/msa/gateway/security/JwtUtil.java
  gateway/src/main/resources/application.yml
  http-requests/UserE2E.http
  user/src/main/java/takeoff/logistics_service/msa/user/application/service/UserServiceImpl.java
  user/src/main/java/takeoff/logistics_service/msa/user/infrastructure/config/SecurityConfig.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/request/PostLoginRequestDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/response/PostLoginResponseDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/external/UserExternalController.java
  user/src/main/resources/application.yml
Labels: ✨ feat, ♻️ refactor, ⚙️ setting

#89 Feature/#81 [delivery] 배송 생성 시 배송 경로가 처음부터 끝까지 모두 생성 #81
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/delivery/domain/entity/DeliveryId.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/delivery/infrastructure/persistence/JpaDeliveryRepository.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/application/client/HubClient.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/application/client/dto/request/PostHubRouteRequestDto.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/application/client/dto/response/HubRoute.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/application/client/dto/response/PostHubRouteResponseDto.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/application/dto/request/PostDeliveryRoutesRequestDto.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/application/dto/response/DeliveryRouteDto.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/application/dto/response/GetDeliveryRouteResponseDto.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/application/service/DeliveryRouteService.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/domain/entity/ActualArrivalInfo.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/domain/entity/DeliveryRoute.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/domain/entity/DeliveryRouteId.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/domain/repository/DeliveryRouteRepository.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/infrastructure/persistence/JpaDeliveryRouteRepository.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/presentation/dto/request/PostDeliveryRoutesRequest.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/presentation/dto/response/DeliveryRouteApi.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/presentation/dto/response/GetDeliveryRoutesResponse.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/presentation/internal/DeliveryRouteInternalController.java
  order/src/main/java/takeoff/logistics_service/msa/order/application/client/DeliveryClient.java
  order/src/main/java/takeoff/logistics_service/msa/order/application/client/dto/request/PostDeliveryRoutesRequestDto.java
  order/src/main/java/takeoff/logistics_service/msa/order/application/service/OrderService.java
  order/src/main/java/takeoff/logistics_service/msa/order/domain/entity/OrderId.java
  order/src/main/java/takeoff/logistics_service/msa/order/domain/entity/OrderItemId.java
  order/src/main/java/takeoff/logistics_service/msa/order/infrastructure/persistence/JpaOrderRepository.java
Labels: ✨ feat

#97 feature/#96: API Gateway 실행 오류 및 코드 리팩토링
  auth/src/main/resources/application.yml
  gateway/src/main/java/takeoff/logistics_service/msa/gateway/security/GatewayJwtFilter.java
  gateway/src/main/java/takeoff/logistics_service/msa/gateway/security/GatewaySecurityConfig.java
  gateway/src/main/resources/application.yml
Labels: 🐛 bug

#99 feature/#98: 회원가입, 사용자 검증(내부 호출), 로그인, 외부 API 호출 E2E 테스트 완료
  auth/src/main/java/takeoff/logistics_service/msa/auth/infrastructure/config/SecurityConfig.java
  auth/src/main/java/takeoff/logistics_service/msa/auth/infrastructure/security/JwtAuthenticationFilter.java
  auth/src/main/resources/application.yml
  gateway/src/main/resources/application.yml
  http-requests/UserE2E.http
  user/src/main/java/takeoff/logistics_service/msa/user/application/service/UserServiceImpl.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/repository/UserRepository.java
  user/src/main/java/takeoff/logistics_service/msa/user/infrastructure/config/SecurityConfig.java
  user/src/main/java/takeoff/logistics_service/msa/user/infrastructure/persistence/JpaUserRepository.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/response/UserValidationResponseDto.java
Labels: ✨ feat, ♻️ refactor

#102 feature/#100 권한 체크 어노테이션 구성 및 회원 가입 및 인증 게이트웨이 오류 수정
  auth/build.gradle
  auth/src/main/java/takeoff/logistics_service/msa/auth/infrastructure/security/JwtAuthenticationFilter.java
  auth/src/main/resources/application.yml
  common/src/main/java/takeoff/logistics_service/msa/common/annotation/RoleCheck.java
  common/src/main/java/takeoff/logistics_service/msa/common/annotation/RoleCheckAspect.java
  gateway/build.gradle
  gateway/src/main/java/takeoff/logistics_service/msa/gateway/GatewayApplication.java
  gateway/src/main/java/takeoff/logistics_service/msa/gateway/security/GatewayJwtFilter.java
  gateway/src/main/java/takeoff/logistics_service/msa/gateway/security/GatewaySecurityConfig.java
  gateway/src/main/resources/application.yml
  http-requests/UserE2E.http
  slack/src/main/java/takeoff/logistics_service/msa/slack/application/service/SlackService.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/application/service/SlackServiceImpl.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/external/SlackExternalController.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/internal/SlackInternalController.java
  slack/src/test/java/takeoff/logistics_service/msa/slack/httpclient/slackHttpClient.http
  slack/src/test/java/takeoff/logistics_service/msa/slack/presentation/external/SlackExternalControllerTest.java
  slack/src/test/java/takeoff/logistics_service/msa/slack/presentation/internal/SlackInternalControllerTest.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/service/UserServiceImpl.java
Labels: ✨ feat, 🐛 bug

#104 feature/#92 각 엔드포인트 권한 설정
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/application/service/HubService.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/application/service/HubServiceImpl.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/presentation/external/HubExternalController.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/presentation/internal/HubInternalController.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/presentation/external/HubRouteExternalController.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/presentation/internal/HubRouteInternalController.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/infrastructure/client/ai/AiPromptEnum.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/external/SlackExternalController.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/internal/SlackInternalController.java
Labels: ✨ feat

#105 Feature/#95 권한검사, 리팩토링
  common/src/main/java/takeoff/logistics_service/msa/common/domain/UserInfoDto.java
  common/src/main/java/takeoff/logistics_service/msa/common/resolver/UserInfoArgumentResolver.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/dto/response/GetUserResponseDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/exception/ProductErrorCode.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/service/ProductService.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/service/ProductServiceImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/service/UserClient.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/domain/entity/Product.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignCompanyClientImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignHubClientImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignStockClientImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignUserClient.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignUserClientImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/dto/response/GetUserResponse.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/presentation/external/ProductExternalController.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/dto/response/GetUserResponseDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/exception/StockErrorCode.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/service/StockService.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/service/StockServiceImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/service/UserClient.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/domain/entity/Stock.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/domain/repository/StockRepository.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/client/FeignUserClient.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/client/FeignUserClientImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/client/dto/response/GetUserResponse.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/persistence/JpaStockRepository.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/external/StockExternalController.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/presentation/internal/StockInternalController.java
  product/src/main/resources/http/stock/internal.http
  product/src/test/java/takeoff/logistics_service/msa/product/product/presentation/external/ProductExternalControllerTest.java
  product/src/test/java/takeoff/logistics_service/msa/product/stock/presentation/external/StockExternalControllerTest.java
  product/src/test/java/takeoff/logistics_service/msa/product/stock/presentation/internal/StockInternalControllerTest.java
Labels: ✨ feat

#111 feature/#101: hubId기준으로 업체 배송담당자, 허브 배송담당자 전체 리스트 조회 앤드포인트 API 구현, co…
  gateway/src/main/java/takeoff/logistics_service/msa/gateway/security/GatewayJwtFilter.java
  gateway/src/main/java/takeoff/logistics_service/msa/gateway/security/GatewaySecurityConfig.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/client/CompanyClient.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/client/HubClient.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/dto/GetCompanyFeignResponse.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/dto/GetHubFeignResponse.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/service/DeliveryManagerService.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/service/DeliveryManagerServiceImpl.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/service/UserService.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/service/UserServiceImpl.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/CompanyDeliveryManager.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/CompanyManager.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/Employee.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/HubDeliveryManager.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/HubManager.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/repository/UserRepository.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/vo/DeliverySequence.java
  user/src/main/java/takeoff/logistics_service/msa/user/infrastructure/persistence/JpaUserRepository.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/request/PostDeliveryManagerRequestDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/request/PostSignupRequestDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/response/GetDeliveryManagerListInfoDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/response/GetDeliveryManagerListInternalResponseDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/response/GetDeliveryManagerResponseDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/response/GetManagerListInfoDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/response/GetManagerListInternalResponseDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/response/GetUserListInfoDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/response/PatchDeliveryManagerResponseDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/response/PostDeliveryManagerResponseDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/internal/DeliveryManagerInternalController.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/internal/UserInternalController.java
Labels: ✨ feat, ♻️ refactor

#117 Feature/#113 config 모듈 추가
  config/build.gradle
  config/configures/hub/hub-local.yml
  config/configures/hub/hub-test.yml
  config/configures/hub/hub.yml
  config/configures/product/product-local.yml
  config/configures/product/product-test.yml
  config/configures/product/product.yml
  config/configures/slack/slack-local.yml
  config/configures/slack/slack-test.yml
  config/configures/slack/slack.yml
  config/gradle/wrapper/gradle-wrapper.jar
  config/gradle/wrapper/gradle-wrapper.properties
  config/src/main/java/takeoff/logistics_service/msa/config/ConfigApplication.java
  config/src/main/resources/application.yml
  hub/build.gradle
  hub/src/main/resources/bootstrap.yml
  product/build.gradle
  product/src/main/resources/application-test.yml
  product/src/main/resources/application.yml
  product/src/main/resources/bootstrap.yml
  settings.gradle
  slack/build.gradle
  slack/src/main/resources/application.yml
  slack/src/main/resources/bootstrap.yml
Labels: ✨ feat

#114 feature/#110 slack 서킷 브레이커 설정 및 테스트
  hub/build.gradle
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/application/service/HubRouteServiceImpl.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/infrastructure/client/feign/FeignHubClientImpl.java
  hub/src/main/resources/application.yml
  hub/src/test/java/takeoff/logistics_service/msa/hub/hub/presentation/external/HubExternalControllerTest.java
  slack/build.gradle
  slack/src/main/java/takeoff/logistics_service/msa/slack/application/exception/SlackErrorCode.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/application/service/SlackAlarmService.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/application/service/SlackServiceImpl.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/infrastructure/client/ai/GeminiWebClient.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/dto/response/PostContentsResponse.java
  slack/src/test/java/takeoff/logistics_service/msa/slack/httpclient/circuitBreakerTest.http
  slack/src/test/java/takeoff/logistics_service/msa/slack/httpclient/slackHttpClient.http
  slack/src/test/java/takeoff/logistics_service/msa/slack/presentation/external/SlackExternalControllerTest.java
Labels: ✨ feat

#119 Feature/#116 그라파나 프로메테우스 설정 및 테스트
  docker-compose.yml
  hub/build.gradle
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/application/service/HubRouteServiceImpl.java
  hub/src/test/java/takeoff/logistics_service/msa/hub/http/HubRouteInternal.http
  product/build.gradle
  server/build.gradle
  server/src/main/resources/application.yml
  server/src/main/resources/prometheus.yml
  slack/build.gradle
  slack/src/test/java/takeoff/logistics_service/msa/slack/httpclient/slackHttpClient.http
Labels: ✨ feat

#123 feature#112-2 : 보상트랜잭션, 타임아웃설정
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/exception/ProductErrorCode.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/service/ProductServiceImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/domain/entity/Product.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/domain/repository/ProductRepository.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignStockClientImpl.java
  product/src/main/resources/application.yml
  product/src/main/resources/http/product/external.http
Labels: ♻️ refactor

#118 feature#112 : 트랜잭션분리
  common/src/main/java/takeoff/logistics_service/msa/common/domain/UserInfoDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/exception/ProductErrorCode.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/service/ProductServiceImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/domain/repository/ProductRepository.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignStockClientImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/service/StockServiceImpl.java
  product/src/main/resources/application.yml
  product/src/main/resources/http/product/external.http
Labels: ✨ feat

#125 Feature/#124 feignclient 연동 확인 및 헤더 추가
  common/build.gradle
  common/src/main/java/takeoff/logistics_service/msa/common/config/FeignClientConfig.java
  config/configures/hub/hub.yml
  gateway/src/main/java/takeoff/logistics_service/msa/gateway/security/GatewayJwtFilter.java
  gateway/src/main/java/takeoff/logistics_service/msa/gateway/security/GatewaySecurityConfig.java
  gateway/src/main/resources/application.yml
  hub/src/main/resources/application.yml
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/dto/response/GetUserResponseDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/service/ProductServiceImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/application/service/UserClient.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignCompanyClient.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignHubClient.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignHubClientImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignStockClient.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignStockClientImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignUserClient.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignUserClientImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/dto/response/GetManagerListResponse.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/dto/response/GetUserResponse.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/dto/response/GetUserResponseDto.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/service/StockServiceImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/application/service/UserClient.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/client/FeignUserClient.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/client/FeignUserClientImpl.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/client/dto/response/GetManagerListResponse.java
  product/src/main/java/takeoff/logistics_service/msa/product/stock/infrastructure/client/dto/response/GetUserResponse.java
  product/src/main/resources/http/product/client.http
  product/src/main/resources/http/product/external.http
  product/src/main/resources/http/stock/internal.http
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/CompanyManager.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/HubDeliveryManager.java
Labels: 🐛 bug

#108 Feature/#90 [delivery] 배송 담당자에게 지정된 마지막 순번 관리 #90
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/DeliverySequence/application/DeliverySequenceService.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/DeliverySequence/application/client/UserClient.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/DeliverySequence/application/client/response/GetDeliveryManagerListInfoDto.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/DeliverySequence/application/client/response/GetDeliveryManagerListInternalResponseDto.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/DeliverySequence/application/dto/request/GetCompanyDeliverySequenceRequestDto.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/DeliverySequence/application/dto/response/GetCompanyDeliverySequenceResponseDto.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/DeliverySequence/application/dto/response/GetHubDeliverySequenceResponseDto.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/DeliverySequence/domain/entity/CompanyDeliverySequence.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/DeliverySequence/domain/entity/HubDeliverySequence.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/DeliverySequence/domain/repository/CompanyDeliverySequenceRepository.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/DeliverySequence/domain/repository/HubDeliverySequenceRepository.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/DeliverySequence/infrastructure/JpaCompanyDeliverySequenceRepository.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/DeliverySequence/infrastructure/JpaHubDeliverySequenceRepository.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/DeliverySequence/presentation/dto/request/GetCompanyDeliverySequenceRequest.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/DeliverySequence/presentation/dto/response/GetCompanyDeliverySequenceResponse.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/DeliverySequence/presentation/dto/response/GetHubDeliverySequenceResponse.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/DeliverySequence/presentation/internal/DeliverySequenceInternalController.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/delivery/application/DeliveryService.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/delivery/application/client/DeliverySequenceClientInternalDelivery.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/delivery/application/client/dto/request/GetCompanyDeliverySequenceRequestDto.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/delivery/application/client/dto/response/GetCompanyDeliverySequenceResponseDto.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/delivery/domain/entity/Delivery.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/delivery/presentation/dto/request/PostDeliveryRequestDto.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/application/client/DeliverySequenceClientInternalDeliveryRoute.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/application/client/dto/response/GetHubDeliverySequenceResponseDto.java
  delivery/src/main/java/takeoff/logisticsservice/msa/delivery/deliveryRoute/application/service/DeliveryRouteService.java
  order/src/main/java/takeoff/logistics_service/msa/order/application/client/CompanyClient.java
  order/src/main/java/takeoff/logistics_service/msa/order/application/client/DeliveryClient.java
  order/src/main/java/takeoff/logistics_service/msa/order/application/client/dto/response/GetCompanyResponseDto.java
  order/src/main/java/takeoff/logistics_service/msa/order/application/service/OrderService.java
  order/src/main/java/takeoff/logistics_service/msa/order/presentation/dto/request/PostOrderRequest.java
Labels: ✨ feat

#134 Refactor/#126 허브 캐싱 수정 및 각 기능 테스트 완료
  hub/build.gradle
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/application/dto/HubIdsDto.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/application/dto/PaginatedResultDto.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/application/dto/request/SearchHubRequestDto.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/application/dto/response/HubToHubResponseDto.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/application/dto/response/PaginatedResultDtoList.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/application/dto/response/PaginatedResultHubResponseDto.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/application/service/HubService.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/application/service/HubServiceImpl.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/domain/repository/HubRepository.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/infrastructure/persistence/JpaHubRepository.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/infrastructure/persistence/impl/JpaHubRepositoryCustomImpl.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/presentation/dto/response/HubToHubResponse.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/presentation/dto/response/PaginatedResultHubResponse.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/presentation/external/HubExternalController.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/presentation/internal/HubInternalController.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/infrastructure/client/feign/FeignHubClientImpl.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/infrastructure/config/RedisConfig.java
  hub/src/main/resources/application-test.yml
  hub/src/main/resources/application.yml
  hub/src/test/java/takeoff/logistics_service/msa/hub/http/Hub.http
  hub/src/test/java/takeoff/logistics_service/msa/hub/http/HubCreate.http
  hub/src/test/java/takeoff/logistics_service/msa/hub/http/HubRouteExternal.http
  hub/src/test/java/takeoff/logistics_service/msa/hub/http/HubRouteInternal.http
  hub/src/test/java/takeoff/logistics_service/msa/hub/hub/application/service/HubServiceImplTest.java
  hub/src/test/java/takeoff/logistics_service/msa/hub/hub/presentation/external/HubExternalControllerTest.java
  hub/src/test/java/takeoff/logistics_service/msa/hub/hub/presentation/internal/HubInternalControllerTest.java
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/persistence/impl/JpaProductRepositoryCustomImpl.java
  slack/src/test/java/takeoff/logistics_service/msa/slack/httpclient/slackHttpClient.http
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/HubDeliveryManager.java
Labels: ♻️ refactor

#136 Refactor/#135 slack 최종 점검 및 테스트 완료
  order/src/main/java/takeoff/logistics_service/msa/order/application/client/UserClient.java
  order/src/main/java/takeoff/logistics_service/msa/order/application/exception/OrderBusinessException.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/infrastructure/persistence/impl/JpaSlackRepositoryCustomImpl.java
  slack/src/main/java/takeoff/logistics_service/msa/slack/presentation/external/SlackExternalController.java
Labels: ♻️ refactor

#131 Fix/#130 스웨거 및 인증 관련 설정 수정
  gateway/src/main/java/takeoff/logistics_service/msa/gateway/security/GatewayJwtFilter.java
  product/build.gradle
  product/src/main/resources/http/product/client.http
  product/src/main/resources/http/product/external.http
  product/src/test/java/takeoff/logistics_service/msa/product/ProductApplicationTests.java
  product/src/test/java/takeoff/logistics_service/msa/product/stock/application/service/StockServiceConcurrencyTest.java
  user/src/main/java/takeoff/logistics_service/msa/user/infrastructure/config/SecurityConfig.java
Labels: 🐛 bug

#138 feature#137 : 상품생성시나리오 작성
  product/src/main/resources/http/product/companymanager.http
  product/src/main/resources/http/product/hunmanager.http
Labels: ✨ feat, ✅ test

#121 feature/#120: 업체 생성 및 수정할 때 관리 허브ID가 존재하는지 검증하는 기능 추가
  company/src/main/java/takeoff/logistics_service/msa/company/CompanyApplication.java
  company/src/main/java/takeoff/logistics_service/msa/company/application/client/HubInternalClient.java
  company/src/main/java/takeoff/logistics_service/msa/company/application/exception/CompanyErrorCode.java
  company/src/main/java/takeoff/logistics_service/msa/company/application/service/CompanyServiceImpl.java
  user/src/main/java/takeoff/logistics_service/msa/user/UserApplication.java
Labels: ✨ feat

#132 Feature#122: 코드 리팩토링, 글로벌 예외처리구현, 권한검증
  auth/build.gradle
  auth/src/main/java/takeoff/logistics_service/msa/auth/application/client/UserServiceFeignClient.java
  auth/src/main/java/takeoff/logistics_service/msa/auth/application/exception/AuthBusinessException.java
  auth/src/main/java/takeoff/logistics_service/msa/auth/application/exception/AuthErrorCode.java
  auth/src/main/java/takeoff/logistics_service/msa/auth/infrastructure/security/JwtAuthenticationFilter.java
  auth/src/main/java/takeoff/logistics_service/msa/auth/infrastructure/security/JwtUtil.java
  auth/src/main/resources/application.yml
  company/build.gradle
  company/src/main/java/takeoff/logistics_service/msa/company/application/client/HubInternalClient.java
  company/src/main/java/takeoff/logistics_service/msa/company/application/service/CompanyService.java
  company/src/main/java/takeoff/logistics_service/msa/company/application/service/CompanyServiceImpl.java
  company/src/main/java/takeoff/logistics_service/msa/company/domain/entity/Company.java
  company/src/main/java/takeoff/logistics_service/msa/company/presentation/external/CompanyExternalController.java
  company/src/main/java/takeoff/logistics_service/msa/company/presentation/internal/CompanyInternalController.java
  http-requests/UserE2E.http
  user/build.gradle
  user/src/main/java/takeoff/logistics_service/msa/user/UserApplication.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/client/CompanyClient.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/client/HubClient.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/exception/UserBusinessException.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/exception/UserErrorCode.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/service/DeliveryManagerService.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/service/DeliveryManagerServiceImpl.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/service/UserService.java
  user/src/main/java/takeoff/logistics_service/msa/user/application/service/UserServiceImpl.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/DeliveryManager.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/HubDeliveryManager.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/User.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/repository/UserSpecifications.java
  user/src/main/java/takeoff/logistics_service/msa/user/infrastructure/persistence/JpaUserRepository.java
  user/src/main/java/takeoff/logistics_service/msa/user/infrastructure/persistence/custom/CustomUserRepository.java
  user/src/main/java/takeoff/logistics_service/msa/user/infrastructure/persistence/custom/CustomUserRepositoryImpl.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/request/GetDeliveryManagerListRequestDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/request/GetUserListRequestDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/external/DeliveryManagerExternalController.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/external/UserExternalController.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/internal/DeliveryManagerInternalController.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/internal/UserInternalController.java
Labels: ✨ feat, ♻️ refactor

#140 Refactor/#139 검증중
  company/build.gradle
  company/src/main/java/takeoff/logistics_service/msa/company/application/client/HubInternalClient.java
  company/src/main/java/takeoff/logistics_service/msa/company/application/service/CompanyServiceImpl.java
  company/src/main/resources/application.yml
  http-requests/integraion/product/StockIntegrationE2ETest.http
  http-requests/integraion/product/StockInternalIntegrationE2ETest.http
  http-requests/integraion/product/productIntegrationE2ETest.http
  http-requests/integraion/user/baseUserCompanyManager.http
  http-requests/integraion/user/baseUserCopanyDeliveryManager.http
  http-requests/integraion/user/baseUserHubDeliveryManager.http
  http-requests/integraion/user/baseUserHubManager.http
  http-requests/integraion/user/baseUserMaster.http
  http-requests/productE2E.http
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/infrastructure/client/feign/FeignHubClient.java
  hub/src/test/java/takeoff/logistics_service/msa/hub/http/Hub.http
  product/src/main/java/takeoff/logistics_service/msa/product/product/infrastructure/client/FeignUserClient.java
  slack/src/test/java/takeoff/logistics_service/msa/slack/httpclient/slackHttpClient.http
  user/src/main/java/takeoff/logistics_service/msa/user/application/service/DeliveryManagerServiceImpl.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/vo/HubId.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/request/PostDeliveryManagerRequestDto.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/external/DeliveryManagerExternalController.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/internal/DeliveryManagerInternalController.java
Labels: 🐛 bug, ♻️ refactor

#142 refactor/#141 배송, 주문 제외 모든 로직 검증
  http-requests/integraion/hub/HubExternalIntegrationE2ETest.http
  http-requests/integraion/hub/HubInternalIntegrationE2ETest.http
  http-requests/integraion/hub/HubRouteExternalIntegrationE2ETest.http
  http-requests/integraion/hub/HubRouteInternalIntegrationE2ETest.http
  http-requests/integraion/product/StockIntegrationE2ETest.http
  http-requests/integraion/product/StockInternalIntegrationE2ETest.http
  http-requests/integraion/slack/SlackIntegrationExternalE2ETest.http
  http-requests/integraion/slack/SlackIntegrationInternalE2ETest.http
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/application/dto/PaginatedResultDto.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/application/dto/feign/AllHubListResponseDto.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/application/service/HubService.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/application/service/HubServiceImpl.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/infrastructure/persistence/JpaHubRepository.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/presentation/dto/feign/AllHubListResponse.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hub/presentation/internal/HubInternalController.java
  hub/src/main/java/takeoff/logistics_service/msa/hub/hubroute/application/service/HubRouteServiceImpl.java
  hub/src/test/java/takeoff/logistics_service/msa/hub/http/HubRouteInternal.http
  hub/src/test/java/takeoff/logistics_service/msa/hub/hub/presentation/internal/HubInternalControllerTest.java
Labels: 🐛 bug, ✅ test

#144 refactor/#143 업체 배송 담당자, 허브 배송 담당자 시퀀스 로직 설정 및 데이터 추가
  http-requests/integraion/user/baseUserHubDeliveryManager.http
  http-requests/integraion/user/deliveryManager/CompanyDeliveryManagerCreate1.http
  http-requests/integraion/user/deliveryManager/CompanyDeliveryManagerCreate10.http
  http-requests/integraion/user/deliveryManager/CompanyDeliveryManagerCreate11.http
  http-requests/integraion/user/deliveryManager/CompanyDeliveryManagerCreate12.http
  http-requests/integraion/user/deliveryManager/CompanyDeliveryManagerCreate13.http
  http-requests/integraion/user/deliveryManager/CompanyDeliveryManagerCreate14.http
  http-requests/integraion/user/deliveryManager/CompanyDeliveryManagerCreate15.http
  http-requests/integraion/user/deliveryManager/CompanyDeliveryManagerCreate16.http
  http-requests/integraion/user/deliveryManager/CompanyDeliveryManagerCreate17.http
  http-requests/integraion/user/deliveryManager/CompanyDeliveryManagerCreate2.http
  http-requests/integraion/user/deliveryManager/CompanyDeliveryManagerCreate3.http
  http-requests/integraion/user/deliveryManager/CompanyDeliveryManagerCreate4.http
  http-requests/integraion/user/deliveryManager/CompanyDeliveryManagerCreate5.http
  http-requests/integraion/user/deliveryManager/CompanyDeliveryManagerCreate6.http
  http-requests/integraion/user/deliveryManager/CompanyDeliveryManagerCreate7.http
  http-requests/integraion/user/deliveryManager/CompanyDeliveryManagerCreate8.http
  http-requests/integraion/user/deliveryManager/CompanyDeliveryManagerCreate9.http
  http-requests/integraion/user/deliveryManager/DelivertyManagerCreate.http
  user/src/main/java/takeoff/logistics_service/msa/user/application/service/DeliveryManagerServiceImpl.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/CompanyDeliveryManager.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/DeliveryManager.java
  user/src/main/java/takeoff/logistics_service/msa/user/domain/entity/HubDeliveryManager.java
  user/src/main/java/takeoff/logistics_service/msa/user/presentation/dto/request/PostDeliveryManagerRequestDto.java
Labels: 🐛 bug, ♻️ refactor, ✅ test
